### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'content'

### ISSUE THREAD

**Issue by leo-smi** [leogregianin/bancocentralbrasil#12]
from bc.bancocentral import Cambio

cambio = Cambio()
print(cambio.get_dolar_compra())

**Comment by leogregianin** [comment]
```
>>> from bc.bancocentral import Cambio
>>> cambio = Cambio()
>>> print(cambio.get_dolar_compra())
4.2443
>>>
```
Olá @leo-smi, qual versão do python está testando e em qual sistema operacional?

**Comment by leo-smi** [comment]
versão 3.7.4, realmente agora funcionou..um tanto quando estranho.

**Comment by leogregianin** [comment]
> versão 3.7.4, realmente agora funcionou..um tanto quando estranho.

Deve ter sido alguma inconsistência momentânea no site do Banco Central.

**Comment by leo-smi** [comment]
É o seguinte, estou tentando requisitar algumas informações, estou tentando fazer isso via bot do telegram rodando na nuvem do pythonanywhere, só que o site bloqueia alguns domínios (ele só permite as que estão na whitelist deles).
Devo sugerir para eles adicionarem o domínio https://conteudo.bcb.gov.br/ ?
Eles possuem os domínios api.bcb.gov.br e olinda.bcb.gov.br, mas acho que ainda assim continua bloqueado pois a biblioteca faz a rota conteudo.bcb.gov.br..... Só que eles requerem a url da API e da doc..

**Comment by leogregianin** [comment]
A rota conteudo.bcb.gov.br já está na whitelist. \o/ 
Teste como ficou e reporta aqui por favor.

**Comment by leo-smi** [comment]
Eu mandei email pra eles, liberaram mesmo. Assim que tiver um tempinho vou usar. Dedos cruzados 🤞

**Comment by leo-smi** [comment]
Se quiser testar meu bot no telegram procura por @leosmi_bot e chama um /info pra ver as funcionalidades

**Comment by leo-smi** [comment]
Se quiser testar o bot, ele está funcionando só procurar por @leosmi_bot manda um /menu , ele está meio lento devido ao fato da conta do servidor ser de graça, ele pode não funcionar ás vezes...Se quiser que libero o código do bot pode entrar em contato que posto aqui no git.

**Comment by leogregianin** [comment]
Testei o bot e ficou muito legal, parabéns mesmo. Se puder liberar o código-fonte no seu próprio repositório seria muito legal também.

**Comment by leo-smi** [comment]
Feito!

**Comment by leogregianin** [comment]
Só pra deixar a referência registrada aqui: https://github.com/leo-smi/Telegram-bot-Banco-Central-do-Brasil-PythonAnywhere-

Algumas coisas que seriam legais ter no seu repo:
* Seguir um padrão de nomes de projetos com letras minúsculas e o espaço substituido por hifen.
* criar o arquivo requirements.txt com os pacotes de dependências para facilitar a instalação.
* faça uma documentação inicial do projeto, por exemplo, como instalar, como usar, telas seriam legais também.

Só algumas dicas. Parabéns pelo projeto.

**Comment by leo-smi** [comment]
Obrigado amigo, reservarei um tempo pra organizar meu repo com sua dicas. Obrigado!
