### ISSUE TITLE
Problemas

### ISSUE THREAD

**Issue by nossi00** [leogregianin/bancocentralbrasil#14]
E ai galera, otima iniciativa de voces em criar esta biblioteca. Porém estou tento problemas para importar o dados de vocês.

Tentei como "bancocentral", "bancocentralbrasil", porém não obtive sucesso. 
![image](https://user-images.githubusercontent.com/59965756/86170809-15dedb00-baf2-11ea-895d-5d52b8f10a94.png)

**Comment by leogregianin** [comment]
Olá @nossi00,
Faça a importação desta forma: 
```python
from bc.bancocentral import Cambio, Selic, Inflacao
```
ou 
```python
bc.bancocentral
```

**Comment by leogregianin** [comment]
Vou fechar essa issue, se tiver alguma dúvida pode reabrí-la.
