### ISSUE TITLE
links

### ISSUE THREAD

**Issue by lucas85cunha** [leogregianin/bancocentralbrasil#2]
Vcs lembra como conseguiu os links para os dados?
http://servicos.albertino.eti.br/
Nesse site o cara fez um webservice para disponibilizar dados. 
Mas esse seu parece que não é leitura de tela.
Att

**Comment by leogregianin** [comment]
Neste projeto é utilizado o RSS disponibilizado pelo Banco Central. Os links seguem abaixo;

Taxas: http://conteudo.bcb.gov.br/api/feed/pt-br/PAINEL_INDICADORES/inflacao
Poupança: http://conteudo.bcb.gov.br/api/feed/pt-br/PAINEL_INDICADORES/poupanca
Dólar: http://conteudo.bcb.gov.br/api/feed/pt-br/PAINEL_INDICADORES/cambio
Juros: http://conteudo.bcb.gov.br/api/feed/pt-br/PAINEL_INDICADORES/juros
