### ISSUE TITLE
computer locked

### ISSUE THREAD

**Issue by a850020** [leogregianin/bancocentralbrasil#5]
Hello, have u ever get this message?

"Prezado Cliente, o acesso desse computador foi bloqueado por identificarmos fragilidade de segurança no equipamento. Para regularizar o acesso nessa máquina, será necessário efetuar a formatação completa e alterar suas senhas.Providencie as cópias de segurança dos seus arquivos e procure um técnico de confiança para o procedimento de formatação."

**Comment by leogregianin** [comment]
Spam message. Closed.
